easy_admin:
    site_name: 'TOP - Manager Panel'
    entities:
        News:
            class: App\Entity\News
            list:
                fields:
                    - { property: 'Title' }
                    - { property: 'Date'}
                    - { property: 'image', type: 'image' ,  base_path: 'uploads/files/' }
            form:
                fields:
                    - { property: 'Title' }
                    - { property: 'Date'}
                    - { property: 'Content', type: 'text_editor' }
                    - { type: 'group', css_class: 'col-sm-4', label: 'Attachments', icon: 'paperclip' }
                    - { property: 'imageFile', type: 'vich_image', type_options: { required: false} }
        Notice:
            class: App\Entity\Notice
            list:
                fields:
                    - { property: 'Title' }
                    - { property: 'Date'}
                    - { property: 'photo', type: 'image' ,  base_path: '..\uploads\files\' }
            form:
                fields:
                    - { property: 'Title' }
                    - { property: 'Date'}
                    - { property: 'Content', type: 'text_editor' }
                    - { type: 'group', css_class: 'col-sm-4', label: 'Attachments', icon: 'paperclip' }
                    - { property: 'imageFile', type: 'vich_image', type_options: { required: false } }
        User:
            class: App\Entity\User
        Subject:
            class: App\Entity\Subject
